#!/bin/bash


##################################
# 初期設定
##################################

# 参考：https://qiita.com/magicant/items/f3554274ee500bddaca8
set -Ceu

# 設定ファイルの読み込み
. `dirname $0`/conf.txt

COMMAND_NAME="dk"


##################################
# 関数置き場
##################################

function open_proglearn_directory () {
  echo "[Info] Please choose the directory..."
  # 配列の中身を全て取り出すには ${HOGE[@]}
  DIR_NAME=($(ls $PROGLEARN_DIRECTORY))
  select VAR in ${DIR_NAME[@]}
  do
    echo $VAR
    echo "Wait to open $PROGLEARN_DIRECTORY/$VAR in Code Editor."
    echo "$CODE_EDITOR $PROGLEARN_DIRECTORY/$VAR"
    $CODE_EDITOR $PROGLEARN_DIRECTORY/$VAR
    break
  done
}

function exec_project () {
  echo "[Info] Please choose projects you want to execute..."
  EXEC_DIRECTORY=`dirname $0`/exec
  PROJECT_NAME=($(ls -F $EXEC_DIRECTORY | grep -v /))
  select VAR in ${PROJECT_NAME[@]}
  do
    echo $VAR
    cd `dirname $0`/exec
    eval `cat $VAR`
    break
  done
}

##################################
# コードの本体
##################################

if [ $# -ge 1 ]; then
  case "$1" in
    "open" | "o") open_proglearn_directory ;;
    "search" | "s" )
      cd `dirname $0`
      node ./_src/google-search/search.js ${@:2}
      ;;
    "exec" | "e") exec_project ;;
    "stop" | "s") stop_project ;;
    "where" | "w") echo `dirname $0`;;
  esac
else
  echo -e "[Warning]Please set command\npgln open"
fi

# exec /bin/zsh
